name: Java
on:
  push:
    branches:
      - master
      - 'releases/**'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v1

    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.8
      with:
        name: ${{ github.repository }} 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
